version: "3.5"

networks:
  proxy:
    name: example
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24

volumes:
  mongodbdata:
  mysqldata:
  postgresqldata:

services:
  mongodb:
    image: mongo:5.0-focal
    container_name: mongodb
    restart: always
    networks:
      - proxy
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    networks:
      - proxy
    ports:
      - 6379:6379

  mysql:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - proxy
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456

  postgresql:
    image: postgres
    restart: always
    networks:
      - proxy
    ports:
      - 5432:5432
    volumes:
      - postgresqldata:/data/db
    environment:
      POSTGRES_PASSWORD: 123456

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080