version: "3.5"

networks:
  proxy:
    name: example
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24

volumes:
  mongodb_data:
  postgres_data:
  mysql_data:

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile_mongodb
    container_name: mongodb
    hostname: mongodb
    restart: always
    networks:
      - proxy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    restart: always
    networks:
      - proxy
    ports:
      - 6379:6379

  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
