version: "3.5"

networks:
  proxy:
    name: example
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24

volumes:
  mongodbdata:
  postgres_data:
  mysql_data:

services:
  mongodb:
    image: mongo:5.0-focal
    container_name: mongodb
    restart: always
    networks:
      - proxy
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    networks:
      - proxy
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
